### ISSUE TITLE
Preview Image

### ISSUE THREAD

**Issue by ChazUK** [jaumard/flare_loading#1]
Would be good to see a preview image of the animation

**Comment by jaumard** [comment]
What do you mean ?

**Comment by ChazUK** [comment]
You don't have any gif's or images of what the animation actually looks like, so the only way people can tell is to test the package themselves.

**Comment by ChazUK** [comment]
Example: https://github.com/leonzone/loading

**Comment by jaumard** [comment]
But it's because this package doesn't offer any animation :) you need to use the animation you want with it. There is no Flare files provided with this package. It's only to make easy the use of a flare animation as loading. All flare files available are there: https://www.2dimensions.com
